development:
  adapter: mysql
  encoding: utf8
  host: localhost
  username: root
#  password: root
  database: idealogue
  
test:
  adapter: mysql
  encoding: utf8
  host: localhost
  username: root
  password: root
  database: test