development:
  adapter: mysql
  encoding: utf8
  host: localhost
  username: root
  #password: root
  database: eventist

test:
  adapter: mysql
  encoding: utf8
  host: localhost
  username: root
  #password: root
  database: test
