development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 500
  
test:
  adapter: mysql
  encoding: utf8
  host: localhost
  username: root
  password: root
  database: test